---
name: CI

on:
  push:
    branches:
      - master
      - 'releases/*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    strategy:
      matrix:
        platform: ['iOS Simulator,name=iPhone 8']
    steps:
      - uses: actions/checkout@v1
      - name: Analyze and Test
        run: |
          xcodebuild clean analyze test \
            -destination "platform=${{ matrix.platform }}" \
            -sdk "iphonesimulator" \
            -project PINCache.xcodeproj \
            -scheme PINCache \
            ONLY_ACTIVE_ARCH=NO \
            CODE_SIGNING_REQUIRED=NO \
            CLANG_ANALYZER_OUTPUT=plist-html \
            CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang" \
           | xcpretty
          if [[ -n `find $(pwd)/clang -name "*.html"` ]] ; then rm -rf $(pwd)/clang; exit 1; fi
          rm -rf $(pwd)/clang
  cocoapods:
    name: CocoaPods
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: pod lib lint
  carthage:
    name: Carthage
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update
        run: carthage update --no-use-binaries --no-build
      - name: Build
        run: carthage build --no-skip-current
  SPM-Build:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12_beta.app/Contents/Developer
    steps:
      - name: "Add GitHub to the SSH known hosts file"
        run: |
          for ip in $(dig @8.8.8.8 github.com +short); do \
            ssh-keyscan github.com,$ip; \
            ssh-keyscan $ip; \
          done 2>/dev/null >> ~/.ssh/known_hosts
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify that PINCache can be build by SPM
        run: xcrun swift build
