---
name: CI

on:
  push:
    branches:
      - master
      - 'releases/*'
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
      matrix:
        platform: ['iOS Simulator,name=iPhone 8']
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: make test
  analyze:
    name: Analyze
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: analyze
        run: make analyze
  cocoapods:
    name: CocoaPods
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: make cocoapods
  carthage:
    name: Carthage
    runs-on: macOS-latest
    env:
      # Carthage is broken in Xcode 12 and above https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md
      DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: carthage
        run: make carthage
  swift-package-manager:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Verify that PINCache can be build by SPM
        run: make spm
  xcode-spm-integration:
    name: Build iOS example project 
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.1.1.app/Contents/Developer
      IOS_EXAMPLE_PROJECT: IntegrationTests/PINCache-SPM-Integration/PINCache-SPM-Integration.xcodeproj
      EXAMPLE_SCHEME: PINCache-SPM-Integration
    strategy:
      matrix:
        destination: ["name=iPhone 12 Pro"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check Xcode's spm integration
        run: |
          set -o pipefail
          xcodebuild clean build -project "${{ env.IOS_EXAMPLE_PROJECT }}" -scheme "${{ env.EXAMPLE_SCHEME }}" -destination "${{ matrix.destination }}" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO